### ISSUE TITLE
Add Folder Note - Horizontal Scrollbar

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/hpi#518]
See the screenshot below.  Even though the screen is really wide, there's still a horizontal scrollbar:

![image](https://cloud.githubusercontent.com/assets/1377228/5631147/d119c18a-9589-11e4-8af4-4424f0c95a73.png)

From quickly playing around in chrome, it looks like the issue is the following CSS:

```css
#folderNotes .notes-wrapper {
  overflow: auto;
  clear: both;
}
```

Removing the `overflow: auto` removes the scrollbar.  However, I'm not sure if that was put there for a reason, or if removing it will break something else.
